const KEY='wdompet_v2_transactions';
const FUNDS='wdompet_v2_funds';
const TRANSFERS='wdompet_v2_transfers';
const BUDGET='wdompet_v2_budget';
const THEME='wdompet_theme';
const $=id=>document.getElementById(id);
const read=(key,fallback=[])=>{try{return JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback))}catch{return fallback}};
let tx=read(KEY),funds=read(FUNDS),transfers=read(TRANSFERS);
const now=new Date(),today=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0)}
function monthKey(d){return String(d||'').slice(0,7)}
function selected(){return $('monthFilter')?.value||monthKey(today)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function shortMoney(n){n=Number(n)||0;if(n>=1000000)return 'Rp'+(n/1000000).toFixed(1).replace('.0','')+' jt';if(n>=1000)return 'Rp'+Math.round(n/1000)+' rb';return 'Rp'+Math.round(n)}
function initMonths(){const el=$('monthFilter');if(!el)return;let arr=[...new Set([monthKey(today),...tx.map(x=>monthKey(x.date))])].filter(Boolean).sort().reverse();el.innerHTML=arr.map(m=>`<option value="${m}">${new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option>`).join('');if(!arr.includes(el.value))el.value=monthKey(today)}
function chartMonths(){let base=new Date(selected()+'-01T00:00:00'),arr=[];for(let i=5;i>=0;i--){let d=new Date(base.getFullYear(),base.getMonth()-i,1);arr.push(d.toISOString().slice(0,7))}return arr}
function chartHtml(){let months=chartMonths(),values=months.map(m=>{let rows=tx.filter(x=>monthKey(x.date)===m);return{m,inc:rows.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),out:rows.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0)}});if(values.every(x=>x.inc===0&&x.out===0))return '<div class="chart-empty"><b>Belum ada data arus kas</b><span>Tambahkan transaksi untuk melihat grafik 6 bulan.</span></div>';let max=Math.max(1,...values.flatMap(x=>[x.inc,x.out])),W=760,H=270,L=48,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,x=i=>L+(i/(values.length-1))*iw,y=v=>T+ih-(v/max)*ih,fmt=m=>new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'short'}).replace('.',''),path=k=>values.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v[k]).toFixed(1)).join(' '),grid=[0,.25,.5,.75,1].map(p=>{let yy=T+ih-p*ih;return`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="gridline"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="axis">${shortMoney(max*p)}</text>`}).join(''),labels=values.map((v,i)=>`<text x="${x(i)}" y="${H-14}" text-anchor="middle" class="axis">${fmt(v.m)}</text>`).join(''),dots=values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v.inc)}" r="4" class="point pin"/><circle cx="${x(i)}" cy="${y(v.out)}" r="4" class="point pout"/>`).join('');return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Grafik pemasukan dan pengeluaran enam bulan"><g>${grid}</g><path d="${path('inc')}" class="line income-line"/><path d="${path('out')}" class="line expense-line"/>${dots}${labels}</svg><div class="chart-summary"><span>Terakhir: <b>${money(values[5].inc)}</b> masuk</span><span><b>${money(values[5].out)}</b> keluar</span></div>`}
function renderChart(){let html=chartHtml();if($('cashChart'))$('cashChart').innerHTML=html;if($('reportCashChart'))$('reportCashChart').innerHTML=html}
function renderCategories(target,data){if(!target)return;let rows=data.filter(x=>x.type==='expense').reduce((a,x)=>{a[x.category]=(a[x.category]||0)+Number(x.amount);return a},{}),list=Object.entries(rows).sort((a,b)=>b[1]-a[1]),max=list[0]?.[1]||1;target.innerHTML=list.length?list.slice(0,8).map(([cat,val],i)=>`<div class="catrow" style="animation-delay:${i*.06}s"><div class="cathead"><span>${esc(cat)}</span><b>${money(val)}</b></div><div class="cattrack"><i style="width:${Math.round(val/max*100)}%"></i></div></div>`).join(''):'<div class="empty">Belum ada pengeluaran.</div>'}
function renderInsights(inc,out,data){if(!$('insights'))return;let balance=inc-out,budget=Number(localStorage.getItem(BUDGET+'_'+selected())||0),largest=data.filter(x=>x.type==='expense').sort((a,b)=>b.amount-a.amount)[0],items=[['Kondisi',balance>=0?`Surplus ${money(balance)}`:`Defisit ${money(Math.abs(balance))}`],['Transaksi',`${data.length} transaksi tercatat`]];if(largest)items.push(['Terbesar',`${esc(largest.category)} • ${money(largest.amount)}`]);if(budget)items.push(['Anggaran',`${Math.round(out/budget*100)}% terpakai`]);$('insights').innerHTML=items.map((x,i)=>`<div class="insight-item" style="animation-delay:${i*.08}s"><span>${x[0]}</span><p><b>${x[1]}</b></p></div>`).join('')}
function budgetValue(){return Number(localStorage.getItem(BUDGET+'_'+selected())||0)}
function renderBudget(inc,out){if(!$('budgetInput'))return;let budget=budgetValue(),pct=budget?Math.round(out/budget*100):0;if($('budgetInput'))$('budgetInput').value=budget||'';if($('progressBar'))$('progressBar').style.width=Math.min(100,pct)+'%';if($('budgetPercent'))$('budgetPercent').textContent=pct+'%';if($('budgetText'))$('budgetText').textContent=budget?`${money(out)} dari ${money(budget)}`:'Belum ada anggaran';let remaining=budget-out;if($('budgetInsight'))$('budgetInsight').innerHTML=(budget?[['Status',remaining>=0?`Sisa ${money(remaining)}`:`Melebihi ${money(Math.abs(remaining))}`],['Rasio',`${pct}% dari anggaran telah digunakan`]]:[['Status','Belum ada anggaran untuk periode ini'],['Saran','Tetapkan batas pengeluaran agar kontrol keuangan lebih mudah.']]).map(x=>`<div class="insight-item"><span>${x[0]}</span><p><b>${x[1]}</b></p></div>`).join('')}
function renderReports(inc,out){if(!$('reportBalance'))return;$('reportBalance').textContent=money(inc-out);$('reportIncome').textContent=money(inc);$('reportExpense').textContent=money(out);renderCategories($('reportCategoryChart'),tx.filter(x=>monthKey(x.date)===selected()))}
function render(){let m=selected(),data=tx.filter(x=>monthKey(x.date)===m),inc=data.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),out=data.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0),balance=inc-out;if($('balance'))$('balance').textContent=money(balance);if($('income'))$('income').textContent=money(inc);if($('expense'))$('expense').textContent=money(out);if($('incomeMini'))$('incomeMini').textContent=money(inc);if($('expenseMini'))$('expenseMini').textContent=money(out);if($('ratioMini'))$('ratioMini').textContent=inc?Math.round(out/inc*100)+'%':'0%';if($('balanceStatus'))$('balanceStatus').textContent=balance>=0?'● Keuangan positif':'● Pengeluaran melebihi pemasukan';if($('transactionMeta'))$('transactionMeta').textContent=data.length+' transaksi';if($('list'))renderTransactionList(data);renderChart();renderCategories($('categoryChart'),data);renderInsights(inc,out,data);renderBudget(inc,out);renderReports(inc,out);renderFunds()}
function renderTransactionList(data){let q=($('search')?.value||'').toLowerCase(),f=$('typeFilter')?.value||'all';data=data.filter(x=>(f==='all'||x.type===f)&&[x.date,x.category,x.note,x.type].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);$('list').innerHTML=data.map(x=>`<tr><td>${new Date(x.date+'T00:00:00').toLocaleDateString('id-ID')}</td><td><span class="badge ${x.type}">${x.type==='income'?'Pemasukan':'Pengeluaran'}</span></td><td>${esc(x.category)}</td><td>${esc(x.note||'-')}</td><td class="${x.type==='income'?'plus':'minus'}">${x.type==='income'?'+':'-'} ${money(x.amount)}</td><td>${esc(fundName(x.fundId))}</td><td><button class="edit" data-id="${esc(x.id)}">Edit</button> <button class="del" data-id="${esc(x.id)}">Hapus</button></td></tr>`).join('');if($('empty'))$('empty').style.display=data.length?'none':'block'}
function fundName(id){return funds.find(f=>f.id===id)?.name||'-'}
function fundBalances(){let b={};funds.forEach(f=>b[f.id]=Number(f.openingBalance)||0);tx.forEach(x=>{if(x.fundId&&b[x.fundId]!=null)b[x.fundId]+=x.type==='income'?Number(x.amount):-Number(x.amount)});transfers.forEach(t=>{if(b[t.fromFundId]!=null)b[t.fromFundId]-=Number(t.amount);if(b[t.toFundId]!=null)b[t.toFundId]+=Number(t.amount)});return b}
function fundOptions(select,selectedId=''){if(!select)return;select.innerHTML='<option value="">Pilih sumber dana</option>'+funds.filter(f=>f.active!==false).map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('');if(selectedId)select.value=selectedId}
function renderFunds(){let target=$('fundList');if(!target)return;let balances=fundBalances();if($('fundMeta'))$('fundMeta').textContent=funds.length+' sumber dana';target.innerHTML=funds.length?`<table><thead><tr><th>Nama</th><th>Jenis</th><th>Keterangan</th><th>Saldo</th><th>Aksi</th></tr></thead><tbody>${funds.map(f=>`<tr><td><b>${esc(f.name)}</b></td><td><span class="fund-badge">${({bank:'Bank',ewallet:'E-Wallet',cash:'Tunai',other:'Lainnya'})[f.type]||'Lainnya'}</span></td><td>${esc(f.masked||'-')}</td><td class="fund-balance">${money(balances[f.id])}</td><td><button class="fund-del" data-fund-id="${esc(f.id)}">Hapus</button></td></tr>`).join('')}</tbody></table>`:'<div class="fund-empty">Belum ada sumber dana.</div>';fundOptions($('fundSelect'));fundOptions($('transferFrom'));fundOptions($('transferTo'))}
function saveFund(){let name=$('fundName')?.value.trim();if(!name)return alert('Nama sumber dana wajib diisi.');let f={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,type:$('fundType').value,openingBalance:Number($('fundOpening').value)||0,masked:$('fundMasked').value.trim(),active:true,created:Date.now()};funds.push(f);save(FUNDS,funds);$('fundName').value='';$('fundOpening').value='';$('fundMasked').value='';renderFunds()}
function removeFund(id){if(!confirm('Hapus sumber dana ini?'))return;if(tx.some(x=>x.fundId===id)||transfers.some(x=>x.fromFundId===id||x.toFundId===id))return alert('Sumber dana masih digunakan transaksi/transfer.');funds=funds.filter(f=>f.id!==id);save(FUNDS,funds);renderFunds()}
function saveTransfer(){let from=$('transferFrom')?.value,to=$('transferTo')?.value,amount=Number($('transferAmount')?.value),date=$('transferDate')?.value||today;if(!from||!to||from===to)return alert('Pilih sumber dana asal dan tujuan yang berbeda.');if(!Number.isFinite(amount)||amount<=0)return alert('Nominal transfer tidak valid.');let b=fundBalances();if((b[from]||0)<amount)return alert('Saldo sumber dana tidak mencukupi.');transfers.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date,fromFundId:from,toFundId:to,amount,note:$('transferNote')?.value.trim()||'',created:Date.now()});save(TRANSFERS,transfers);if($('transferAmount'))$('transferAmount').value='';if($('transferNote'))$('transferNote').value='';renderFunds();render()}
function exportCsv(){let rows=[['Tanggal','Jenis','Kategori','Keterangan','Nominal','Sumber Dana'],...tx.map(x=>[x.date,x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.note,x.amount,fundName(x.fundId)])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='wdompet-transaksi.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0)}
function startEdit(id){sessionStorage.setItem('wdompet_edit_id',id);location.href='tambah.html'}
function bind(){if($('date')&&!$('date').value)$('date').value=today;if($('transferDate')&&!$('transferDate').value)$('transferDate').value=today;if($('monthFilter'))$('monthFilter').addEventListener('change',render);if($('search'))$('search').addEventListener('input',render);if($('typeFilter'))$('typeFilter').addEventListener('change',render);if($('list'))$('list').addEventListener('click',e=>{let edit=e.target.closest('.edit'),del=e.target.closest('.del');if(edit)startEdit(edit.dataset.id);if(del)removeTx(del.dataset.id)});if($('form')){$('form').addEventListener('submit',saveTransaction);prepareEdit()}if($('saveBudget'))$('saveBudget').addEventListener('click',()=>{let n=Number($('budgetInput').value)||0;localStorage.setItem(BUDGET+'_'+selected(),String(Math.max(0,n)));render()});if($('saveFund'))$('saveFund').addEventListener('click',saveFund);if($('fundList'))$('fundList').addEventListener('click',e=>{let b=e.target.closest('.fund-del');if(b)removeFund(b.dataset.fundId)});if($('saveTransfer'))$('saveTransfer').addEventListener('click',saveTransfer);if($('themeToggle'))$('themeToggle').addEventListener('click',toggleTheme);if($('exportBtn'))$('exportBtn').addEventListener('click',exportCsv);if($('reportExport'))$('reportExport').addEventListener('click',exportCsv)}
function prepareEdit(){let id=sessionStorage.getItem('wdompet_edit_id'),item=tx.find(x=>x.id===id);if(!item)return;if($('formTitle'))$('formTitle').textContent='Edit Transaksi';if($('saveTransaction'))$('saveTransaction').textContent='Simpan Perubahan';if($('date'))$('date').value=item.date;if($('type'))$('type').value=item.type;if($('category'))$('category').value=item.category;if($('amount'))$('amount').value=item.amount;if($('note'))$('note').value=item.note||'';if($('fundSelect'))fundOptions($('fundSelect'),item.fundId)}
function newId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())}
function saveTransaction(e){e.preventDefault();let amount=Number($('amount')?.value);if(!Number.isFinite(amount)||amount<=0)return alert('Nominal tidak valid.');let id=sessionStorage.getItem('wdompet_edit_id'),item=tx.find(x=>x.id===id);let data={id:id||newId(),type:$('type').value,date:$('date').value,category:$('category').value.trim(),note:$('note').value.trim(),amount,fundId:$('fundSelect')?.value||'',created:item?.created||Date.now()};if(!data.category)return alert('Kategori wajib diisi.');if(item)tx=tx.map(x=>x.id===id?data:x);else tx.push(data);save(KEY,tx);sessionStorage.removeItem('wdompet_edit_id');e.target.reset();if($('date'))$('date').value=today;initMonths();render();location.href='transaksi.html'}
function removeTx(id){if(!confirm('Hapus transaksi ini?'))return;tx=tx.filter(x=>x.id!==id);save(KEY,tx);initMonths();render()}
function toggleTheme(){let dark=!document.body.classList.contains('theme-dark');document.body.classList.toggle('theme-dark',dark);localStorage.setItem(THEME,dark?'dark':'light');updateThemeButton()}
function updateThemeButton(){if($('themeToggle'))$('themeToggle').textContent=document.body.classList.contains('theme-dark')?'☀':'☼'}
function themeInit(){document.body.classList.toggle('theme-dark',localStorage.getItem(THEME)==='dark');updateThemeButton()}
window.addEventListener('storage',e=>{if(e.key===KEY)tx=read(KEY);if(e.key===FUNDS)funds=read(FUNDS);if(e.key===TRANSFERS)transfers=read(TRANSFERS);if(e.key===KEY||e.key===FUNDS||e.key===TRANSFERS||e.key?.startsWith(BUDGET+'_')){initMonths();render();renderFunds()}if(e.key===THEME){document.body.classList.toggle('theme-dark',e.newValue==='dark');updateThemeButton()}});
bind();themeInit();initMonths();render();renderFunds();