const KEY='wdompet_v2_transactions',FUNDS='wdompet_v2_funds',TRANSFERS='wdompet_v2_transfers',BUDGET='wdompet_v2_budget';
const $=id=>document.getElementById(id),now=new Date(),today=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,10);
let tx=JSON.parse(localStorage.getItem(KEY)||'[]'),funds=JSON.parse(localStorage.getItem(FUNDS)||'[]'),transfers=JSON.parse(localStorage.getItem(TRANSFERS)||'[]');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const monthKey=d=>String(d||'').slice(0,7),selected=()=>$('monthFilter').value;
function uid(){return crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random())}
function saveAll(){localStorage.setItem(KEY,JSON.stringify(tx));localStorage.setItem(FUNDS,JSON.stringify(funds));localStorage.setItem(TRANSFERS,JSON.stringify(transfers))}
function initFunds(){if(!funds.length){funds=[{id:uid(),name:'Tunai',type:'cash',openingBalance:0,masked:'',active:true,created:Date.now()}];localStorage.setItem(FUNDS,JSON.stringify(funds))}let valid=funds.find(f=>f.active);if(valid){tx.forEach(x=>{if(!x.fundId)x.fundId=valid.id});localStorage.setItem(KEY,JSON.stringify(tx))}}
function fundTypeLabel(t){return{bank:'Bank',ewallet:'E-Wallet',cash:'Tunai',other:'Lainnya'}[t]||'Lainnya'}
function fundBalance(id){let f=funds.find(x=>x.id===id);if(!f)return 0;let n=Number(f.openingBalance)||0;tx.forEach(x=>{if(x.fundId===id)n+=x.type==='income'?Number(x.amount):-(Number(x.amount)||0)});transfers.forEach(x=>{if(x.fromFundId===id)n-=Number(x.amount)||0;if(x.toFundId===id)n+=Number(x.amount)||0});return n}
function totalBalance(){return funds.reduce((a,f)=>a+fundBalance(f.id),0)}
function initMonths(){let arr=[...new Set([monthKey(today),...tx.map(x=>monthKey(x.date)),...transfers.map(x=>monthKey(x.date))])].filter(Boolean).sort().reverse();$('monthFilter').innerHTML=arr.map(m=>`<option value="${m}">${new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option>`).join('');if(!arr.includes(monthKey(today)))$('monthFilter').value=arr[0]||monthKey(today)}
function shortMoney(n){n=Number(n)||0;if(n>=1000000)return'Rp'+(n/1000000).toFixed(1).replace('.0','')+' jt';if(n>=1000)return'Rp'+Math.round(n/1000)+' rb';return'Rp'+Math.round(n)}
function chartMonths(){let base=new Date(selected()+'-01T00:00:00'),a=[];for(let i=5;i>=0;i--){let d=new Date(base.getFullYear(),base.getMonth()-i,1);a.push(d.toISOString().slice(0,7))}return a}
function chartHtml(){let vals=chartMonths().map(m=>{let r=tx.filter(x=>monthKey(x.date)===m);return{m,inc:r.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),out:r.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0)}});if(vals.every(x=>!x.inc&&!x.out))return'<div class="chart-empty"><b>Belum ada data arus kas</b><span>Tambahkan transaksi untuk melihat grafik 6 bulan.</span></div>';let max=Math.max(1,...vals.flatMap(x=>[x.inc,x.out])),W=760,H=270,L=48,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,x=i=>L+i/(vals.length-1)*iw,y=v=>T+ih-v/max*ih,fmt=m=>new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'short'}).replace('.',''),path=k=>vals.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v[k]).toFixed(1)).join(' ');let grid=[0,.25,.5,.75,1].map(p=>{let yy=T+ih-p*ih;return`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="gridline"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="axis">${shortMoney(max*p)}</text>`}).join(''),labels=vals.map((v,i)=>`<text x="${x(i)}" y="${H-14}" text-anchor="middle" class="axis">${fmt(v.m)}</text>`).join(''),dots=vals.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v.inc)}" r="4" class="point pin"/><circle cx="${x(i)}" cy="${y(v.out)}" r="4" class="point pout"/>`).join('');return`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Grafik pemasukan dan pengeluaran enam bulan"><g>${grid}</g><path d="${path('inc')}" class="line income-line"/><path d="${path('out')}" class="line expense-line"/>${dots}${labels}</svg>`}
function renderChart(){$('cashChart').innerHTML=chartHtml();$('reportCashChart').innerHTML=chartHtml()}
function renderCategories(target,data){let rows=data.filter(x=>x.type==='expense').reduce((a,x)=>(a[x.category]=(a[x.category]||0)+Number(x.amount),a),{}),list=Object.entries(rows).sort((a,b)=>b[1]-a[1]),max=list[0]?.[1]||1;target.innerHTML=list.length?list.slice(0,8).map(([c,v])=>`<div class="catrow"><div class="cathead"><span>${esc(c)}</span><b>${money(v)}</b></div><div class="cattrack"><i style="width:${Math.round(v/max*100)}%"></i></div></div>`).join(''):'<div class="empty">Belum ada pengeluaran.</div>'}
function renderFunds(target){target.innerHTML=funds.map(f=>`<article class="fund-card"><div class="fund-head"><span class="fund-type">${fundTypeLabel(f.type)}</span><span><i class="status-dot ${f.active?'':'off'}"></i> ${f.active?'Aktif':'Nonaktif'}</span></div><h3>${esc(f.name)}</h3><div class="fund-balance">${money(fundBalance(f.id))}</div><div class="fund-meta">${esc(f.masked||'Saldo sumber dana')}${f.active?'':' • tidak dapat dipakai untuk transaksi baru'}</div><div class="fund-actions"><button data-fund-toggle="${esc(f.id)}">${f.active?'Nonaktifkan':'Aktifkan'}</button>${funds.length>1?`<button class="danger" data-fund-delete="${esc(f.id)}">Hapus</button>`:''}</div></article>`).join('')||'<div class="empty">Belum ada sumber dana.</div>'}
function fillFundSelects(){let active=funds.filter(f=>f.active);$('fundId').innerHTML=active.length?active.map(f=>`<option value="${f.id}">${esc(f.name)} — ${money(fundBalance(f.id))}</option>`).join(''):'<option value="">Tambahkan sumber dana terlebih dahulu</option>';let opts=active.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('');$('fromFund').innerHTML=opts;$('toFund').innerHTML=opts}
function renderFundViews(){renderFunds($('funds'));renderFunds($('homeFunds'));fillFundSelects();$('sourceCount').textContent=funds.filter(f=>f.active).length+' sumber'}
function renderInsights(inc,out,data){let b=inc-out,budget=Number(localStorage.getItem(BUDGET+'_'+selected())||0),largest=data.filter(x=>x.type==='expense').sort((a,b)=>b.amount-a.amount)[0],items=[['Kondisi',b>=0?`Surplus ${money(b)}`:`Defisit ${money(Math.abs(b))}`],['Transaksi',`${data.length} transaksi tercatat`]];if(largest)items.push(['Terbesar',`${esc(largest.category)} • ${money(largest.amount)}`]);if(budget)items.push(['Anggaran',`${Math.round(out/budget*100)}% terpakai`]);$('insights').innerHTML=items.map(x=>`<div class="insight-item"><span>${x[0]}</span><p><b>${x[1]}</b></p></div>`).join('')}
function renderBudget(inc,out){let b=Number(localStorage.getItem(BUDGET+'_'+selected())||0),p=b?Math.round(out/b*100):0;$('budgetInput').value=b||'';$('progressBar').style.width=Math.min(100,p)+'%';$('budgetPercent')&&($('budgetPercent').textContent=p+'%');$('budgetText').textContent=b?`${money(out)} dari ${money(b)}`:'Belum ada anggaran';$('budgetInsight').innerHTML=b?`<div class="insight-item"><span>Status</span><p><b>${out<=b?'Sisa '+money(b-out):'Melebihi '+money(out-b)}</b></p></div>`:'<div class="insight-item"><span>Status</span><p><b>Belum ada anggaran untuk periode ini</b></p></div>'}
function render(){let m=selected(),data=tx.filter(x=>monthKey(x.date)===m),inc=data.filter(x=>x.type==='income').reduce((a,x)=>a+Number(x.amount),0),out=data.filter(x=>x.type==='expense').reduce((a,x)=>a+Number(x.amount),0),bal=totalBalance();$('balance').textContent=money(bal);$('income').textContent=money(inc);$('expense').textContent=money(out);$('ratioMini').textContent=inc?Math.round(out/inc*100)+'%':'0%';$('balanceStatus').textContent=bal>=0?'● Saldo positif':'● Saldo negatif';$('transactionMeta').textContent=data.length+' transaksi';let q=$('search').value.toLowerCase(),f=$('typeFilter').value;data=data.filter(x=>(f==='all'||x.type===f)&&[x.date,x.category,x.note,x.type,x.fundId].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||(b.created||0)-(a.created||0));$('list').innerHTML=data.map(x=>{let fn=funds.find(z=>z.id===x.fundId);return`<tr><td>${new Date(x.date+'T00:00:00').toLocaleDateString('id-ID')}</td><td><span class="badge ${x.type}">${x.type==='income'?'Pemasukan':'Pengeluaran'}</span></td><td>${esc(x.category)}</td><td>${esc(x.note||'-')}</td><td class="${x.type==='income'?'plus':'minus'}">${x.type==='income'?'+':'-'} ${money(x.amount)}</td><td><span class="source-chip">${esc(fn?.name||'Tidak diketahui')}</span></td><td class="action-cell"><button class="edit" data-edit="${esc(x.id)}">Edit</button><button class="del" data-delete="${esc(x.id)}">Hapus</button></td></tr>`}).join('');$('empty').style.display=data.length?'none':'block';renderChart();renderCategories($('categoryChart'),tx.filter(x=>monthKey(x.date)===m));renderInsights(inc,out,tx.filter(x=>monthKey(x.date)===m));renderBudget(inc,out);$('reportBalance').textContent=money(inc-out);$('reportIncome').textContent=money(inc);$('reportExpense').textContent=money(out);renderCategories($('reportCategoryChart'),tx.filter(x=>monthKey(x.date)===m));renderFundViews()}
function resetForm(){let form=$('form');form.reset();$('editId').value='';$('date').value=today;$('formTitle').textContent='Tambah Transaksi';$('saveTx').textContent='Simpan Transaksi';$('cancelEdit').style.display='none';$('formPanel').classList.remove('edit-mode')}
function editTx(id){let x=tx.find(t=>t.id===id);if(!x)return;$('editId').value=x.id;$('date').value=x.date;$('type').value=x.type;$('category').value=x.category;$('amount').value=x.amount;$('fundId').value=x.fundId||funds.find(f=>f.active)?.id||'';$('note').value=x.note||'';$('formTitle').textContent='Edit Transaksi';$('saveTx').textContent='Simpan Perubahan';$('cancelEdit').style.display='inline-block';$('formPanel').classList.add('edit-mode');setView('add')}
function removeTx(id){if(confirm('Hapus transaksi ini?')){tx=tx.filter(x=>x.id!==id);saveAll();initMonths();render()}}
function exportCsv(){let rows=[['Tanggal','Jenis','Kategori','Keterangan','Nominal','Sumber Dana'],...tx.map(x=>[x.date,x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.note,x.amount,funds.find(f=>f.id===x.fundId)?.name||''])],csv=rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='wdompet-transaksi.csv';a.click();URL.revokeObjectURL(a.href)}
function setView(v,hash=true){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.target===v));if(hash)history.replaceState(null,'','#'+v);window.scrollTo({top:0,behavior:'smooth'})}
function viewFromHash(){let h=location.hash.replace('#','');setView(['home','transactions','add','accounts','budget','reports'].includes(h)?h:'home',false)}
$('form').addEventListener('submit',e=>{e.preventDefault();let amount=Number($('amount').value),fid=$('fundId').value;if(!fid)return alert('Pilih sumber dana terlebih dahulu.');if(!Number.isFinite(amount)||amount<=0)return alert('Nominal tidak valid.');let id=$('editId').value;if(id){let x=tx.find(t=>t.id===id);if(x)Object.assign(x,{type:$('type').value,date:$('date').value,category:$('category').value.trim(),note:$('note').value.trim(),amount,fundId:fid})}else tx.push({id:uid(),type:$('type').value,date:$('date').value,category:$('category').value.trim(),note:$('note').value.trim(),amount,fundId:fid,created:Date.now()});saveAll();resetForm();initMonths();$('monthFilter').value=monthKey($('date').value||today);render();setView('home')});
$('cancelEdit').addEventListener('click',resetForm);$('monthFilter').addEventListener('change',render);$('search').addEventListener('input',render);$('typeFilter').addEventListener('change',render);document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.target==='add')resetForm();setView(b.dataset.target)}));document.querySelectorAll('[data-target="accounts"]').forEach(b=>b.addEventListener('click',()=>setView('accounts')));
$('list').addEventListener('click',e=>{let ed=e.target.closest('[data-edit]'),del=e.target.closest('[data-delete]');if(ed)editTx(ed.dataset.edit);if(del)removeTx(del.dataset.delete)});
$('fundForm').addEventListener('submit',e=>{e.preventDefault();let name=$('fundName').value.trim(),opening=Number($('openingBalance').value)||0;if(!name)return;funds.push({id:uid(),name,type:$('fundType').value,openingBalance:opening,masked:$('masked').value.trim(),active:true,created:Date.now()});saveAll();e.target.reset();$('openingBalance').value=0;render()});
$('funds').addEventListener('click',e=>{let t=e.target.closest('[data-fund-toggle]'),d=e.target.closest('[data-fund-delete]');if(t){let f=funds.find(x=>x.id===t.dataset.fundToggle);if(f){f.active=!f.active;saveAll();render()}}if(d){let id=d.dataset.fundDelete;if(tx.some(x=>x.fundId===id)||transfers.some(x=>x.fromFundId===id||x.toFundId===id))return alert('Sumber dana yang sudah memiliki transaksi/transfer tidak dapat dihapus. Nonaktifkan saja.');funds=funds.filter(x=>x.id!==id);saveAll();render()}});
$('transferForm').addEventListener('submit',e=>{e.preventDefault();let from=$('fromFund').value,to=$('toFund').value,amount=Number($('transferAmount').value);if(!from||!to||from===to)return alert('Pilih sumber dana yang berbeda.');if(!Number.isFinite(amount)||amount<=0)return alert('Nominal transfer tidak valid.');if(fundBalance(from)<amount)return alert('Saldo sumber dana tidak mencukupi.');transfers.push({id:uid(),date:$('transferDate').value,fromFundId:from,toFundId:to,amount,note:$('transferNote').value.trim(),created:Date.now()});saveAll();e.target.reset();$('transferDate').value=today;render();alert('Transfer berhasil disimpan.')});
$('saveBudget').addEventListener('click',()=>{let n=Number($('budgetInput').value)||0;localStorage.setItem(BUDGET+'_'+selected(),String(n));render()});$('themeToggle').addEventListener('click',()=>{document.body.classList.toggle('theme-dark');localStorage.setItem('wdompet_theme',document.body.classList.contains('theme-dark')?'dark':'light');$('themeToggle').textContent=document.body.classList.contains('theme-dark')?'☀':'☼'});if(localStorage.getItem('wdompet_theme')==='dark'){document.body.classList.add('theme-dark');$('themeToggle').textContent='☀'}$('exportBtn').addEventListener('click',exportCsv);$('reportExport').addEventListener('click',exportCsv);window.addEventListener('hashchange',viewFromHash);$('transferDate').value=today;$('year').textContent=new Date().getFullYear();initFunds();initMonths();viewFromHash();render();