const KEY='wdompet_v2_transactions'; const BUDGET='wdompet_v2_budget';
const $=id=>document.getElementById(id); let tx=JSON.parse(localStorage.getItem(KEY)||'[]');
const now=new Date(), today=now.toISOString().slice(0,10); $('date').value=today;
function money(n){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n)}
function monthKey(d){return d.slice(0,7)}
function selected(){return $('monthFilter').value}
function initMonths(){let arr=[...new Set([monthKey(today),...tx.map(x=>monthKey(x.date))])].sort().reverse(); $('monthFilter').innerHTML=arr.map(m=>`<option value="${m}">${new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</option>`).join('');$('monthFilter').value=monthKey(today)}
function save(){localStorage.setItem(KEY,JSON.stringify(tx));render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function shortMoney(n){if(n>=1000000)return 'Rp'+(n/1000000).toFixed(1).replace('.0','')+' jt';if(n>=1000)return 'Rp'+Math.round(n/1000)+' rb';return 'Rp'+Math.round(n)}
function chartMonths(){let base=new Date(selected()+'-01T00:00:00');let arr=[];for(let i=5;i>=0;i--){let d=new Date(base.getFullYear(),base.getMonth()-i,1);arr.push(d.toISOString().slice(0,7))}return arr}
function renderChart(){let months=chartMonths(), values=months.map(m=>{let rows=tx.filter(x=>monthKey(x.date)===m);return {m,inc:rows.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),out:rows.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0)}});let max=Math.max(1,...values.flatMap(x=>[x.inc,x.out]));let W=760,H=270,L=48,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B;let x=i=>L+(i/(values.length-1))*iw;let y=v=>T+ih-(v/max)*ih;let fmt=m=>new Date(m+'-01T00:00:00').toLocaleDateString('id-ID',{month:'short'}).replace('.','');let path=key=>values.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v[key]).toFixed(1)).join(' ');let grid=[0,.25,.5,.75,1].map(p=>{let yy=T+ih-p*ih;return `<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="gridline"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="axis">${shortMoney(max*p)}</text>`}).join('');let labels=values.map((v,i)=>`<text x="${x(i)}" y="${H-14}" text-anchor="middle" class="axis">${fmt(v.m)}</text>`).join('');let dots=values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v.inc)}" r="4" class="point pin"/><circle cx="${x(i)}" cy="${y(v.out)}" r="4" class="point pout"/>`).join('');$('cashChart').innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Grafik pemasukan dan pengeluaran enam bulan"><g>${grid}</g><path d="${path('inc')}" class="line income-line"/><path d="${path('out')}" class="line expense-line"/>${dots}${labels}</svg><div class="chart-summary"><span>Terakhir: <b>${money(values[5].inc)}</b> masuk</span><span><b>${money(values[5].out)}</b> keluar</span></div>`}
function renderCategories(data){let rows=data.filter(x=>x.type==='expense').reduce((a,x)=>{a[x.category]=(a[x.category]||0)+x.amount;return a},{});let list=Object.entries(rows).sort((a,b)=>b[1]-a[1]);let max=list[0]?.[1]||1;$('categoryChart').innerHTML=list.length?list.slice(0,6).map(([cat,val],i)=>`<div class="catrow" style="animation-delay:${i*.06}s"><div class="cathead"><span>${esc(cat)}</span><b>${money(val)}</b></div><div class="cattrack"><i style="width:${Math.round(val/max*100)}%"></i></div></div>`).join(''):'<div class="empty">Belum ada pengeluaran.</div>'}
function renderInsights(inc,out,data){let balance=inc-out,budget=Number(localStorage.getItem(BUDGET)||0),largest=data.filter(x=>x.type==='expense').sort((a,b)=>b.amount-a.amount)[0],items=[['Kondisi',balance>=0?`Surplus ${money(balance)}`:`Defisit ${money(Math.abs(balance))}`],['Transaksi',`${data.length} transaksi tercatat`]];if(largest)items.push(['Terbesar',`${esc(largest.category)} • ${money(largest.amount)}`]);if(budget)items.push(['Anggaran',`${Math.round(out/budget*100)}% terpakai`]);$('insights').innerHTML=items.map((x,i)=>`<div class="insight-item" style="animation-delay:${i*.08}s"><span>${x[0]}</span><p><b>${x[1]}</b></p></div>`).join('')}
function render(){let m=selected(), data=tx.filter(x=>monthKey(x.date)===m);let inc=data.filter(x=>x.type==='income').reduce((a,x)=>a+x.amount,0),out=data.filter(x=>x.type==='expense').reduce((a,x)=>a+x.amount,0),balance=inc-out;$('balance').textContent=money(balance);$('income').textContent=money(inc);$('expense').textContent=money(out);$('ratio').textContent=inc?Math.round(out/inc*100)+'%':'0%';$('balanceStatus').textContent=balance>=0?'● Keuangan positif':'● Pengeluaran melebihi pemasukan';$('transactionMeta').textContent=data.length+' transaksi';
$('incomeMini').textContent=money(inc);$('expenseMini').textContent=money(out);$('ratioMini').textContent=inc?Math.round(out/inc*100)+'%':'0%';
let q=$('search').value.toLowerCase(), f=$('typeFilter').value;data=data.filter(x=>(f==='all'||x.type===f)&&[x.date,x.category,x.note,x.type].join(' ').toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date)||b.created-a.created);$('list').innerHTML=data.map(x=>`<tr><td>${new Date(x.date+'T00:00:00').toLocaleDateString('id-ID')}</td><td><span class="badge ${x.type}">${x.type==='income'?'Pemasukan':'Pengeluaran'}</span></td><td>${esc(x.category)}</td><td>${esc(x.note||'-')}</td><td class="${x.type==='income'?'plus':'minus'}">${x.type==='income'?'+':'-'} ${money(x.amount)}</td><td><button class="del" onclick="removeTx('${x.id}')">Hapus</button></td></tr>`).join('');$('empty').style.display=data.length?'none':'block';
renderChart();renderCategories(tx.filter(x=>monthKey(x.date)===m));renderInsights(inc,out,tx.filter(x=>monthKey(x.date)===m));let budget=Number(localStorage.getItem(BUDGET)||0);$('budgetInput').value=budget||'';let pct=budget?Math.round(out/budget*100):0;$('progressBar').style.width=Math.min(100,pct)+'%';$('budgetPercent').textContent=pct+'%';$('budgetText').textContent=budget?`${money(out)} dari ${money(budget)}`:'Belum ada anggaran';}
function removeTx(id){if(confirm('Hapus transaksi ini?')){tx=tx.filter(x=>x.id!==id);initMonths();save()}}
$('form').addEventListener('submit',e=>{e.preventDefault();let amount=Number($('amount').value);if(!Number.isFinite(amount)||amount<=0)return alert('Nominal tidak valid.');tx.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:$('type').value,date:$('date').value,category:$('category').value,note:$('note').value.trim(),amount,created:Date.now()});e.target.reset();$('date').value=today;initMonths();$('monthFilter').value=monthKey(today);save();location.hash='top'});
$('monthFilter').addEventListener('change',render);$('search').addEventListener('input',render);$('typeFilter').addEventListener('change',render);$('saveBudget').addEventListener('click',()=>{let n=Number($('budgetInput').value)||0;localStorage.setItem(BUDGET,String(n));render()});
function exportCsv(){let rows=[['Tanggal','Jenis','Kategori','Keterangan','Nominal'],...tx.map(x=>[x.date,x.type==='income'?'Pemasukan':'Pengeluaran',x.category,x.note,x.amount])];let csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='wdompet-transaksi.csv';a.click()}
$('exportBtn').addEventListener('click',exportCsv);$('exportBottom').addEventListener('click',exportCsv);
document.querySelectorAll('.bottomnav a').forEach(a=>a.addEventListener('click',()=>{document.querySelectorAll('.bottomnav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
initMonths();render();