(function(){
  const KEY='wdompet_v2_transactions';
  const getTx=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
  const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
  const shortMoney=n=>{n=Number(n)||0;if(n>=1000000)return 'Rp'+(n/1000000).toFixed(1).replace('.0','')+' jt';if(n>=1000)return 'Rp'+Math.round(n/1000)+' rb';return 'Rp'+Math.round(n)};
  const rangeLabels={7:'7 Hari',30:'1 Bulan',90:'3 Bulan',180:'6 Bulan'};
  function dateKey(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function bucketData(days,tx){
    const end=new Date();end.setHours(23,59,59,999);const start=addDays(end,-days+1);let buckets=[];
    if(days===7){for(let i=0;i<7;i++){const d=addDays(start,i),key=dateKey(d);buckets.push({key,label:d.toLocaleDateString('id-ID',{day:'numeric',month:'short'}).replace('.',''),inc:0,out:0})}}
    else {const count=days===30?30:days===90?13:26;const step=days===30?1:days===90?7:7;for(let i=0;i<count;i++){const d=addDays(start,i*step);buckets.push({key:dateKey(d),label:days===30?d.toLocaleDateString('id-ID',{day:'numeric',month:'short'}).replace('.',''):d.toLocaleDateString('id-ID',{day:'numeric',month:'short'}).replace('.',''),inc:0,out:0})}}
    const validStart=dateKey(start),validEnd=dateKey(end);
    tx.forEach(x=>{if(!x.date||x.date<validStart||x.date>validEnd)return;const d=new Date(x.date+'T00:00:00');let idx;if(days===7)idx=Math.round((d-start)/86400000);else if(days===30)idx=Math.round((d-start)/86400000);else idx=Math.min(buckets.length-1,Math.floor((d-start)/86400000/7));if(idx>=0&&buckets[idx]){if(x.type==='income')buckets[idx].inc+=Number(x.amount)||0;else if(x.type==='expense')buckets[idx].out+=Number(x.amount)||0}});
    return buckets;
  }
  function render(target,days){if(!target)return;const tx=getTx(),values=bucketData(days,tx);if(values.every(v=>v.inc===0&&v.out===0)){target.innerHTML='<div class="chart-empty"><b>Belum ada data arus kas</b><span>Tambahkan transaksi untuk melihat grafik.</span></div>';return}const max=Math.max(1,...values.flatMap(v=>[v.inc,v.out])),W=760,H=270,L=48,R=18,T=18,B=42,iw=W-L-R,ih=H-T-B,x=i=>L+(i/(values.length-1||1))*iw,y=v=>T+ih-(v/max)*ih,grid=[0,.25,.5,.75,1].map(p=>{const yy=T+ih-p*ih;return`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" class="gridline"/><text x="${L-8}" y="${yy+4}" text-anchor="end" class="axis">${shortMoney(max*p)}</text>`}).join(''),path=k=>values.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v[k]).toFixed(1)).join(' '),dots=values.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v.inc)}" r="4" class="point pin"/><circle cx="${x(i)}" cy="${y(v.out)}" r="4" class="point pout"/>`).join(''),labels=values.map((v,i)=>`<text x="${x(i)}" y="${H-14}" text-anchor="middle" class="axis">${v.label}</text>`).join('');const last=values[values.length-1];target.innerHTML=`<div class="chart-range-head"><label>Rentang<select class="chart-range-select"><option value="7" ${days===7?'selected':''}>7 Hari</option><option value="30" ${days===30?'selected':''}>1 Bulan</option><option value="90" ${days===90?'selected':''}>3 Bulan</option><option value="180" ${days===180?'selected':''}>6 Bulan</option></select></label></div><svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Grafik pemasukan dan pengeluaran ${rangeLabels[days]}"><g>${grid}</g><path d="${path('inc')}" class="line income-line"/><path d="${path('out')}" class="line expense-line"/>${dots}${labels}</svg><div class="chart-summary"><span>Terakhir: <b>${money(last.inc)}</b> masuk</span><span><b>${money(last.out)}</b> keluar</span></div>`;target.querySelector('.chart-range-select').addEventListener('change',e=>{const value=Number(e.target.value);localStorage.setItem('wdompet_chart_range',String(value));render(target,value)})}
  function init(){const saved=Number(localStorage.getItem('wdompet_chart_range'));const days=[7,30,90,180].includes(saved)?saved:180;['cashChart','reportCashChart'].forEach(id=>{const el=document.getElementById(id);if(el)render(el,days)})}
  window.addEventListener('storage',e=>{if(e.key===KEY)init()});window.addEventListener('wdompet:updated',init);init();
})();
