(function(){
  const internal={};
  let running=false,pending=false,timer=0,ready=false;
  const getData=()=>window.wdompetGetData?.()||{funds:[],tx:[],transfers:[],budgets:{}};
  async function getUser(){try{const r=await window.wdompetSupabase?.auth.getUser();return r?.data?.user||null}catch{return null}}
  async function loadRemote(user){const s=window.wdompetSupabase,out={};for(const n of ['sumber_dana','transaksi','transfer','anggaran']){const r=await s.from(n).select('*').eq('user_id',user.id);if(r.error)throw r.error;out[n]=r.data||[]}return out}
  function remoteToData(r){const source=r.sumber_dana||[];const funds=source.map(x=>({id:x.client_id||String(x.id),name:x.name,type:x.type,openingBalance:Number(x.opening_balance)||0,masked:x.masked||'',active:x.active!==false,created:new Date(x.created_at||Date.now()).getTime()}));const fundMap=new Map(source.map(x=>[String(x.id),x.client_id||String(x.id)]));const tx=(r.transaksi||[]).map(x=>({id:x.client_id||String(x.id),type:x.type,date:x.date,category:x.category||'',note:x.note||'',amount:Number(x.amount)||0,fundId:fundMap.get(String(x.fund_id))||'',created:new Date(x.created_at||Date.now()).getTime()}));const transfers=(r.transfer||[]).map(x=>({id:x.client_id||String(x.id),date:x.date,fromFundId:fundMap.get(String(x.from_fund_id))||'',toFundId:fundMap.get(String(x.to_fund_id))||'',amount:Number(x.amount)||0,note:x.note||'',created:new Date(x.created_at||Date.now()).getTime()}));const budgets={};(r.anggaran||[]).forEach(x=>{budgets[String(x.month).slice(0,7)]=Number(x.amount)||0});return{funds,tx,transfers,budgets}}
  async function deleteMissing(s,user,table,rows,ids){const keep=new Set(ids.map(String));for(const row of rows){if(row.client_id&&!keep.has(String(row.client_id))){const r=await s.from(table).delete().eq('user_id',user.id).eq('client_id',row.client_id);if(r.error)throw r.error}}}
  async function pushData(user){const s=window.wdompetSupabase,data=getData(),localFunds=data.funds||[],localTx=data.tx||[],localTransfers=data.transfers||[],budgets=data.budgets||{};const fundRows=localFunds.map(f=>({user_id:user.id,client_id:String(f.id),name:f.name,type:f.type,opening_balance:Number(f.openingBalance)||0,masked:f.masked||'',active:f.active!==false}));if(fundRows.length){const r=await s.from('sumber_dana').upsert(fundRows,{onConflict:'user_id,client_id'});if(r.error)throw r.error}const fr=await s.from('sumber_dana').select('id,client_id').eq('user_id',user.id);if(fr.error)throw fr.error;const fmap=new Map((fr.data||[]).map(x=>[String(x.client_id),x.id]));const txRows=localTx.map(x=>({user_id:user.id,client_id:String(x.id),fund_id:fmap.get(String(x.fundId))||null,category_id:null,date:x.date,type:x.type,category:x.category||'',note:x.note||'',amount:Number(x.amount)||0}));if(txRows.length){const r=await s.from('transaksi').upsert(txRows,{onConflict:'user_id,client_id'});if(r.error)throw r.error}const trRows=localTransfers.map(x=>({user_id:user.id,client_id:String(x.id),from_fund_id:fmap.get(String(x.fromFundId)),to_fund_id:fmap.get(String(x.toFundId)),date:x.date,amount:Number(x.amount)||0,note:x.note||''})).filter(x=>x.from_fund_id&&x.to_fund_id);if(trRows.length){const r=await s.from('transfer').upsert(trRows,{onConflict:'user_id,client_id'});if(r.error)throw r.error}const budgetRows=Object.entries(budgets).filter(([m])=>/^\d{4}-\d{2}$/.test(m)).map(([m,a])=>({user_id:user.id,client_id:m,month:m+'-01',amount:Math.max(0,Number(a)||0)}));if(budgetRows.length){const r=await s.from('anggaran').upsert(budgetRows,{onConflict:'user_id,client_id'});if(r.error)throw r.error}const remote=await loadRemote(user);await deleteMissing(s,user,'transaksi',remote.transaksi,localTx.map(x=>x.id));await deleteMissing(s,user,'transfer',remote.transfer,localTransfers.map(x=>x.id));await deleteMissing(s,user,'anggaran',remote.anggaran,Object.keys(budgets));await deleteMissing(s,user,'sumber_dana',remote.sumber_dana,localFunds.map(x=>x.id))}
  async function initialSync(){if(running){pending=true;return}if(!window.wdompetSupabase)return;running=true;try{const user=await getUser();if(!user)return;const remote=await loadRemote(user);window.wdompetSetRemoteData?.(remoteToData(remote));ready=true;window.dispatchEvent(new Event('wdompet:synced'))}catch(e){console.error('WDompet Supabase initial sync:',e);ready=false;window.dispatchEvent(new CustomEvent('wdompet:sync-error',{detail:{message:e?.message||String(e),phase:'initial'}}))}finally{running=false;if(pending){pending=false;schedule()}}}
  async function syncChanges(){if(running){pending=true;return false}if(!window.wdompetSupabase)return false;running=true;try{const user=await getUser();if(!user)return false;if(!ready){await initialSync();return false}await pushData(user);ready=true;window.dispatchEvent(new Event('wdompet:synced'));return true}catch(e){console.error('WDompet Supabase save:',e);ready=false;window.dispatchEvent(new CustomEvent('wdompet:sync-error',{detail:{message:e?.message||String(e),phase:'save'}}));return false}finally{running=false;if(pending){pending=false;schedule()}}}
  window.wdompetSyncNow=syncChanges;
  function schedule(){clearTimeout(timer);timer=setTimeout(()=>syncChanges(),500)}
  window.wdompetResetData=async function(){if(!window.wdompetSupabase)return false;const user=await getUser();if(!user)throw new Error('Sesi login tidak ditemukan.');if(!window.confirm('RESET SEMUA DATA KEUANGAN?\n\nSemua transaksi, transfer, anggaran, sumber dana, dan kategori milik akun ini akan dihapus permanen. Akun/login tetap dipertahankan.'))return false;const s=window.wdompetSupabase;for(const table of ['transaksi','transfer','anggaran','sumber_dana','kategori']){const r=await s.from(table).delete().eq('user_id',user.id);if(r.error)throw r.error}window.wdompetSetRemoteData?.({funds:[],tx:[],transfers:[],budgets:{}});ready=true;location.reload();return true};
  if(window.wdompetAuthReady)window.wdompetAuthReady.then(initialSync);else setTimeout(initialSync,800);window.addEventListener('wdompet-auth-ready',initialSync);
})();